import { useEffect, useState } from 'react';
import discoveriesImage from '../assets/waypoint-discoveries.png';

const places = [
  { name: 'Goa', country: 'India', type: 'COASTAL RESET', categories: ['Outdoors', 'Stay'], mood: 'For mornings that begin with the tide and end without a schedule.', prompt: 'Plan a relaxed 4-day Goa trip with quiet beaches, local seafood, sunset walks, and comfortable stays. Avoid crowded party areas.', position: '0% 50%' },
  { name: 'Jaipur', country: 'India', type: 'LIVING HERITAGE', categories: ['Culture', 'Food'], mood: 'For colour, craft, and the pleasure of taking the long way home.', prompt: 'Plan a thoughtful 3-day Jaipur trip with architecture, local crafts, vegetarian food, and a calm pace. Avoid rushed sightseeing.', position: '50% 50%' },
  { name: 'Ladakh', country: 'India', type: 'WIDE OPEN', categories: ['Outdoors', 'Stay'], mood: 'For the kind of silence that puts everything else in perspective.', prompt: 'Plan a gentle 5-day Ladakh trip with acclimatisation, scenic drives, monasteries, easy walks, and practical altitude guidance.', position: '100% 50%' },
  { name: 'Kyoto', country: 'Japan', type: 'QUIET DETAIL', categories: ['Culture', 'Food'], mood: 'For unhurried streets, small rituals, and rooms made for pausing.', prompt: 'Plan a 4-day Kyoto trip focused on gardens, traditional neighbourhoods, tea, seasonal food, and quieter temples.', position: '50% 50%' },
  { name: 'Reykjavík', country: 'Iceland', type: 'ELEMENTAL', categories: ['Outdoors', 'Stay'], mood: 'For weather worth watching and landscapes that reset the scale.', prompt: 'Plan a 5-day Reykjavík and south Iceland trip with waterfalls, hot springs, easy scenic stops, and a realistic driving pace.', position: '100% 50%' },
  { name: 'Marrakech', country: 'Morocco', type: 'SENSE OF PLACE', categories: ['Culture', 'Food', 'Stay'], mood: 'For spice, shade, and an old city that rewards your curiosity.', prompt: 'Plan a 4-day Marrakech trip with markets, gardens, Moroccan food, craft workshops, and a restful riad stay.', position: '0% 50%' },
];
const categories = ['All', 'Outdoors', 'Food', 'Culture', 'Stay'];

export default function Discoveries({ onPlan }) {
  const [category, setCategory] = useState('All');
  const [saved, setSaved] = useState(() => { try { return JSON.parse(localStorage.getItem('waypoint-saved-places') || '[]'); } catch { return []; } });
  useEffect(() => { try { localStorage.setItem('waypoint-saved-places', JSON.stringify(saved)); } catch {} }, [saved]);
  const toggleSave = (name) => setSaved((items) => items.includes(name) ? items.filter((item) => item !== name) : [...items, name]);
  return <section className="discoveries" id="discover"><div className="shell"><div className="discoveries-heading"><div><p className="eyebrow">A WORLD OF GOOD IDEAS</p><h2>Where would you<br />like to feel more alive?</h2></div><p>Choose a place with a feeling behind it. Waypoint turns the idea into an editable route built around your time, pace, and priorities.</p></div><div className="discovery-controls" aria-label="Explore interests">{categories.map((item) => <button className={item === category ? 'active' : ''} key={item} onClick={() => setCategory(item)}>{item}</button>)}<span>{saved.length} saved for later</span></div></div><div className="destination-shelf" aria-label="Suggested destinations" onWheel={(event) => { if (Math.abs(event.deltaY) > Math.abs(event.deltaX)) { event.preventDefault(); event.currentTarget.scrollLeft += event.deltaY; } }}>{places.map((place, index) => <article className={category !== 'All' && !place.categories.includes(category) ? 'destination-card muted' : `destination-card destination-${index % 3}`} key={place.name}><div className="destination-image" style={{ backgroundImage: `url(${discoveriesImage})`, backgroundPosition: place.position }}><div className="destination-image-shade" /><button onClick={() => toggleSave(place.name)} aria-label={`Save ${place.name}`} className={saved.includes(place.name) ? 'saved' : ''}>{saved.includes(place.name) ? 'Saved' : '+'}</button><span>{place.type}</span><div className="destination-title"><small>{place.country}</small><h3>{place.name}</h3></div></div><div className="destination-copy"><p>{place.mood}</p><button onClick={() => onPlan?.(place.prompt)}>Plan this feeling <b>→</b></button></div></article>)}</div></section>;
}
