import { useState } from 'react';

function Stop({ stop, onRemove, onMoveUp, onMoveDown, first, last }) {
  return <article className="stop"><div className="stop-top"><span className="time">{stop.time}</span><div className="stop-actions"><button aria-label={`Move ${stop.name} earlier`} disabled={first} onClick={onMoveUp}>↑</button><button aria-label={`Move ${stop.name} later`} disabled={last} onClick={onMoveDown}>↓</button><button aria-label={`Remove ${stop.name}`} className="remove" onClick={onRemove}>×</button></div></div><h3>{stop.name}</h3><p>{stop.description}</p><div className="stop-meta"><span>◷ {stop.duration}</span>{stop.tip && <span>✦ {stop.tip}</span>}</div></article>;
}

export default function Itinerary({ itinerary, onChange }) {
  const [openDays, setOpenDays] = useState(() => new Set([itinerary.days[0]?.day]));
  const updateStops = (dayIndex, nextStops) => onChange({ ...itinerary, days: itinerary.days.map((day, index) => index === dayIndex ? { ...day, stops: nextStops } : day) });
  return <section className="itinerary"><div className="itinerary-heading"><div><p className="eyebrow">Your custom route</p><h1>{itinerary.title}</h1><p>{itinerary.summary}</p></div><span className="day-count">{itinerary.days.length} days</span></div><div className="day-list">{itinerary.days.map((day, dayIndex) => { const open = openDays.has(day.day); return <section className="day" key={`${day.day}-${dayIndex}`}><button className="day-toggle" onClick={() => setOpenDays((current) => { const next = new Set(current); next.has(day.day) ? next.delete(day.day) : next.add(day.day); return next; })}><span className="day-number">{String(day.day).padStart(2, '0')}</span><span><strong>Day {day.day}</strong><small>{day.title} · {day.stops.length} stops</small></span><span className="chevron">{open ? '−' : '+'}</span></button>{open && <div className="stops">{day.stops.length ? day.stops.map((stop, index) => <Stop key={stop.id} stop={stop} first={index === 0} last={index === day.stops.length - 1} onRemove={() => updateStops(dayIndex, day.stops.filter((item) => item.id !== stop.id))} onMoveUp={() => { const next = [...day.stops]; [next[index - 1], next[index]] = [next[index], next[index - 1]]; updateStops(dayIndex, next); }} onMoveDown={() => { const next = [...day.stops]; [next[index], next[index + 1]] = [next[index + 1], next[index]]; updateStops(dayIndex, next); }} />) : <p className="empty-day">No stops left on this day.</p>}</div>}</section>; })}</div></section>;
}
