import { useEffect, useRef, useState } from 'react';
import PromptInput from './components/PromptInput';
import LoadingState from './components/LoadingState';
import ErrorState from './components/ErrorState';
import Itinerary from './components/Itinerary';
import SavedTrips from './components/SavedTrips';
import TripDashboard from './components/TripDashboard';
import { generateItinerary } from './lib/api';
import { parseItinerary } from './lib/validateResult';

const storageKey = 'waypoint-saved-trips';
const readSaved = () => { try { const trips = JSON.parse(localStorage.getItem(storageKey) || '[]'); return Array.isArray(trips) ? trips.slice(0, 5) : []; } catch { return []; } };
export default function App() {
  const [input, setInput] = useState(''); const [itinerary, setItinerary] = useState(null); const [status, setStatus] = useState('idle'); const [error, setError] = useState(''); const [savedTrips, setSavedTrips] = useState(readSaved); const requestId = useRef(0); const abortRef = useRef(null);
  useEffect(() => () => abortRef.current?.abort(), []); useEffect(() => { try { localStorage.setItem(storageKey, JSON.stringify(savedTrips)); } catch {} }, [savedTrips]);
  const saveTrip = (trip) => { setItinerary(trip); setSavedTrips((items) => [{ id: crypto.randomUUID?.() || String(Date.now()), savedAt: new Date().toISOString(), itinerary: trip }, ...items.filter((item) => item.itinerary.title !== trip.title)].slice(0, 5)); };
  const submit = async (event) => { event.preventDefault(); const brief = input.trim(); if (!brief || status === 'loading') return; abortRef.current?.abort(); const controller = new AbortController(); abortRef.current = controller; const id = ++requestId.current; setStatus('loading'); setError(''); try { const parsed = parseItinerary(await generateItinerary(brief, controller.signal)); if (id !== requestId.current) return; if (!parsed.ok) { setError(parsed.message); setStatus('error'); return; } saveTrip(parsed.data); setStatus('success'); } catch (err) { if (id !== requestId.current || err.name === 'AbortError') return; setError(err.message || 'Something unexpected happened.'); setStatus('error'); } };
  const cancel = () => { requestId.current += 1; abortRef.current?.abort(); setStatus(itinerary ? 'success' : 'idle'); };
  return <main className="app"><header><a className="brand" href="#top"><span>W</span>Waypoint</a><nav><a href="#planner">Plan a trip</a><a href="#saved">My trips</a><a href="#how-it-works">How it works</a></nav><button className="header-action" onClick={() => document.getElementById('trip-request')?.focus()}>Create a plan <span>↗</span></button></header><section className="hero-band" id="top"><div className="shell hero-grid"><div><p className="eyebrow">Independent travel, considered</p><h1>Make room for the <em>good parts.</em></h1><p className="hero-copy">Build a day-by-day route around the places, pace, and moments you actually care about.</p><div className="hero-actions"><button onClick={() => document.getElementById('trip-request')?.focus()}>Start a new trip <span>→</span></button><a href="#how-it-works">See how it works</a></div><div className="trust-row"><span>Personal route</span><span>Easy to adjust</span><span>Yours to keep</span></div></div><div className="hero-postcard" aria-hidden="true"><div className="postcard-stamp">WAYPOINT<br />TRAVEL CLUB</div><p>Go with a plan.<br /><em>Leave space for a story.</em></p><div><span>01</span><b>Curious<br />by nature</b></div></div></div></section><div className="shell planner-shell" id="planner"><div className="planner-intro"><p className="eyebrow">Start with a feeling</p><h2>Where are you headed?</h2><p>Tell us the kind of trip you want. The details are yours to shape afterward.</p></div><PromptInput value={input} onChange={setInput} onSubmit={submit} loading={status === 'loading'} />{status === 'loading' && <LoadingState onCancel={cancel} />}{status === 'error' && <ErrorState message={error} retry={() => submit({ preventDefault() {} })} />}{status === 'success' && <><TripDashboard itinerary={itinerary} /><Itinerary itinerary={itinerary} onChange={saveTrip} /></>}{<div id="saved"><SavedTrips trips={savedTrips} activeTitle={itinerary?.title} onLoad={(trip) => { abortRef.current?.abort(); setItinerary(trip); setStatus('success'); }} onDelete={(id) => setSavedTrips((trips) => trips.filter((trip) => trip.id !== id))} /></div>}<section className="how-it-works" id="how-it-works"><p className="eyebrow">A simple way to plan</p><div><article><span>01</span><h3>Describe the feeling</h3><p>Share your destination, timing, interests, and what you would rather skip.</p></article><article><span>02</span><h3>Shape the route</h3><p>Open each day, reorder stops, and remove anything that does not fit.</p></article><article><span>03</span><h3>Take it with you</h3><p>Plans are saved privately on your device and ready to export.</p></article></div></section></div><footer>Waypoint helps you plan, not book. Always confirm opening hours, availability, local transport, and travel guidance before you go.</footer></main>;
}
