import { useEffect, useRef, useState } from 'react';
import PromptInput from './components/PromptInput';
import LoadingState from './components/LoadingState';
import ErrorState from './components/ErrorState';
import Itinerary from './components/Itinerary';
import SavedTrips from './components/SavedTrips';
import TripDashboard from './components/TripDashboard';
import coastHero from './assets/waypoint-coast-hero.png';
import { generateItinerary } from './lib/api';
import { parseItinerary } from './lib/validateResult';

const storageKey = 'waypoint-saved-trips';
const readSaved = () => { try { const trips = JSON.parse(localStorage.getItem(storageKey) || '[]'); return Array.isArray(trips) ? trips.slice(0, 5) : []; } catch { return []; } };
export default function App() {
  const [input, setInput] = useState(''); const [itinerary, setItinerary] = useState(null); const [status, setStatus] = useState('idle'); const [error, setError] = useState(''); const [savedTrips, setSavedTrips] = useState(readSaved); const requestId = useRef(0); const abortRef = useRef(null);
  useEffect(() => () => abortRef.current?.abort(), []); useEffect(() => { try { localStorage.setItem(storageKey, JSON.stringify(savedTrips)); } catch {} }, [savedTrips]);
  const saveTrip = (trip) => { setItinerary(trip); setSavedTrips((items) => [{ id: crypto.randomUUID?.() || String(Date.now()), savedAt: new Date().toISOString(), itinerary: trip }, ...items.filter((item) => item.itinerary.title !== trip.title)].slice(0, 5)); };
  const submit = async (event) => { event.preventDefault(); const brief = input.trim(); if (!brief || status === 'loading') return; abortRef.current?.abort(); const controller = new AbortController(); abortRef.current = controller; const id = ++requestId.current; setStatus('loading'); setError(''); try { const parsed = parseItinerary(await generateItinerary(brief, controller.signal)); if (id !== requestId.current) return; if (!parsed.ok) { setError(parsed.message); setStatus('error'); return; } saveTrip(parsed.data); setStatus('success'); } catch (err) { if (id !== requestId.current || err.name === 'AbortError') return; setError(err.message || 'Something unexpected happened.'); setStatus('error'); } };
  const cancel = () => { requestId.current += 1; abortRef.current?.abort(); setStatus(itinerary ? 'success' : 'idle'); };
  return <main className="app"><header><a className="brand" href="#top">WAYPOINT</a><nav><a href="#top">Discover</a><a href="#planner">Plan</a><a href="#saved">My trips</a></nav><button className="header-action" onClick={() => document.getElementById('trip-request')?.focus()}>Start planning</button></header><section className="hero-band" id="top"><img src={coastHero} alt="Traveler walking along a quiet coastline" /><div className="hero-copy-block"><p>WAYPOINT / 2026</p><h1>Go somewhere<br />that changes <em>you.</em></h1><button onClick={() => document.getElementById('trip-request')?.focus()}>Plan your escape <span>→</span></button></div><div className="hero-caption"><span>01 — GOA, INDIA</span><span>Travel with intention</span></div></section><div className="shell planner-shell" id="planner"><section className="planner-lede"><p className="eyebrow">A route, made personal</p><h2>Tell us what you<br />want to feel.</h2><p>Share a destination, your timing, and the details that matter. Your route remains flexible from the first idea to the final stop.</p></section><PromptInput value={input} onChange={setInput} onSubmit={submit} loading={status === 'loading'} />{status === 'loading' && <LoadingState onCancel={cancel} />}{status === 'error' && <ErrorState message={error} retry={() => submit({ preventDefault() {} })} />}{status === 'success' && <><TripDashboard itinerary={itinerary} /><Itinerary itinerary={itinerary} onChange={saveTrip} /></>}{<div id="saved"><SavedTrips trips={savedTrips} activeTitle={itinerary?.title} onLoad={(trip) => { abortRef.current?.abort(); setItinerary(trip); setStatus('success'); }} onDelete={(id) => setSavedTrips((trips) => trips.filter((trip) => trip.id !== id))} /></div>}<section className="how-it-works" id="how-it-works"><p className="eyebrow">Designed for the way you travel</p><div><article><span>01</span><h3>One clear brief</h3><p>Say what you want, in your own words. No rigid forms or unnecessary questions.</p></article><article><span>02</span><h3>A route to make yours</h3><p>Open each day, move the stops, and remove anything that does not feel right.</p></article><article><span>03</span><h3>Keep it close</h3><p>Your plans are saved privately on this device and can be exported whenever you need them.</p></article></div></section></div><footer>Waypoint is for planning, not booking. Confirm local hours, availability, transport, and travel guidance before you go.</footer></main>;
}
